language: python
matrix:
  include:
    - name: "Python 3.7.3 on Windows"
      os: windows
      language: shell
      before_install: choco install python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install: pip3 install -r requirements.txt
script: 
  - cd "TF2 Rich Presence"
  - python ci_test_runner.py
