language: python
matrix:
  include:
    - name: "Python 3.7.3 on Windows"
      os: windows
      language: shell
      before_install: choco install python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7
      dist: xenial
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2
      language: shell
install: pip3 install -r requirements.txt
script: 
  - cd "TF2 Rich Presence"
  - python python3 ci_test_runner.py || python ci_test_runner.py
